from django.db import models
from datetime import datetime


class Job(models.Model):
    job_id = models.AutoField(primary_key=True)
    """
    The unique identifier for the job. Automatically generated by Django as an AutoField.
    """

    title = models.CharField(max_length=255)
    """
    The title of the job position. Max length: 255 characters.
    """

    company = models.CharField(max_length=255)
    """
    The name of the company offering the job. Max length: 255 characters.
    """

    company_image_source = models.ImageField(upload_to='company_images/', null=True, blank=True)
    """
    The image source for the company's logo or branding. This image is uploaded to 'company_images/'.
    Can be left blank or null if no image is provided.
    """

    location = models.CharField(max_length=255)
    """
    The location of the job (e.g., city or office location). Max length: 255 characters.
    """

    job_type = models.CharField(max_length=50)
    """
    The type of job (e.g., Full-time, Part-time, Internship). Max length: 50 characters.
    """

    salary = models.CharField(max_length=100)
    """
    The salary range or specific salary for the job. Max length: 100 characters.
    This can be a string such as "Negotiable" or a specific range.
    """

    description = models.TextField()
    """
    A detailed description of the job role, responsibilities, and other relevant information.
    """

    requirements = models.TextField()
    """
    A detailed list of the skills, qualifications, and experience required for the job.
    """

    benefits = models.TextField()
    """
    A list of benefits offered by the company for this job (e.g., health insurance, vacation days).
    """

    industry = models.CharField(max_length=100)
    """
    The industry in which the job is offered (e.g., Technology, Healthcare).
    Max length: 100 characters.
    """

    posting_date = models.DateTimeField(auto_now_add=True)
    """
    The date and time when the job posting was created. Automatically set to the current timestamp.
    """

    expiration_date = models.DateTimeField()
    """
    The date and time when the job posting will expire. After this date, the job posting is no longer valid.
    """

    def __repr__(self):
        return f"Job({self.job_id}, {self.title}, {self.company}, {self.location}, {self.job_type})"

    def is_expired(self):
        """Returns whether the job listing has expired based on the expiration_date."""
        return self.expiration_date < datetime.now()

    class Meta:
        ordering = ['-posting_date']
        """
        Orders jobs by their posting date, displaying the most recent jobs first.
        """


class JobApplication(models.Model):
    job = models.ForeignKey(Job, related_name='applications', on_delete=models.CASCADE)
    """
    The job the applicant is applying for. This is a foreign key to the Job model.
    A job can have multiple applications.
    """

    fullname = models.CharField(max_length=64)
    """
    The full name of the applicant. Max length: 64 characters.
    """

    email = models.EmailField(max_length=64)
    """
    The email address of the applicant. Max length: 64 characters.
    """

    phone = models.CharField(max_length=12)
    """
    The phone number of the applicant. Max length: 12 characters.
    Typically, phone numbers will include the country code (e.g., +263).
    """

    cover_letter = models.TextField(blank=True, null=True)
    """
    A cover letter or statement of interest from the applicant explaining why they are interested in the job 
    and why they are a good fit for the role. This field is optional and can be left blank.
    """

    resume = models.FileField(upload_to='resumes/', max_length=255)
    """
    The applicant's resume file. Uploaded files are stored in the 'resumes/' directory.
    Max file size can be limited in the settings (e.g., max 2MB).
    """

    date_applied = models.DateTimeField(auto_now_add=True)
    """
    The date and time when the application was submitted. Automatically set to the current timestamp.
    """

    def __str__(self):
        return f"Application for {self.job.title} by {self.fullname}"

    class Meta:
        ordering = ['-date_applied']
        """
        Orders applications by the date they were submitted, displaying the most recent applications first.
        """
