# Generated by Django 5.1.5 on 2025-02-18 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsultationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        help_text="The full name of the person requesting the consultation.",
                        max_length=64,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The email address of the person requesting the consultation.",
                        max_length=64,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        help_text="The name of the company the person represents.",
                        max_length=64,
                    ),
                ),
                (
                    "number_employees",
                    models.IntegerField(
                        help_text="The number of employees at the company."
                    ),
                ),
                (
                    "consultancy_service_type",
                    models.CharField(
                        choices=[
                            ("Strategy Consulting", "Strategy Consulting"),
                            (
                                "Human Resources (HR) Consulting",
                                "Human Resources (HR) Consulting",
                            ),
                            ("Operations Consulting", "Operations Consulting"),
                        ],
                        help_text="Type of consultancy service requested (e.g., Strategy, HR, Operations).",
                        max_length=64,
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        help_text="Any additional details the client wants to provide about the consultation.",
                        null=True,
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(
                        help_text="The preferred date for the consultation."
                    ),
                ),
                (
                    "preferred_time",
                    models.TimeField(
                        help_text="The preferred time for the consultation."
                    ),
                ),
                (
                    "consultation_channel",
                    models.CharField(
                        choices=[
                            ("Phone call", "Phone call"),
                            ("Google Meeting", "Google Meeting"),
                        ],
                        help_text="The preferred method of consultation (e.g., Phone call, Google Meeting).",
                        max_length=64,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp of when the consultation request was created.",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=64)),
                ("feedback", models.TextField()),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                (
                    "company_image_source",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_images/"
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("job_type", models.CharField(max_length=50)),
                ("salary", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("benefits", models.TextField()),
                ("industry", models.CharField(max_length=100)),
                ("posting_date", models.DateTimeField(auto_now_add=True)),
                ("expiration_date", models.DateTimeField()),
            ],
            options={
                "ordering": ["-posting_date"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=64)),
                ("phone", models.CharField(max_length=12)),
                ("cover_letter", models.TextField(blank=True, null=True)),
                ("resume", models.FileField(max_length=255, upload_to="resumes/")),
                ("date_applied", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_applied"],
            },
        ),
    ]
