# Generated by Django 5.1.5 on 2025-02-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_job_created_at_job_core_job_created_8e7744_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_image_source",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/company_images"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
